[package]
name = "filereap"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
chrono = "0.4.19"
thiserror = "1.0.30"
serde = { version = "1.0.136", features = ["derive"] }
toml = "0.5.9"
log = "0.4.16"
pretty_env_logger = "0.4.0"
